
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lac_fullstack_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d lac_fullstack_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["backend"]

  api:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/lac_fullstack_dev?sslmode=disable
      - FLASK_APP=app:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    profiles: ["backend"]

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:5000/
      - NEXT_PUBLIC_BASE_URL=http://api:5000/
    #depends_on:
    #  - api
    profiles: ["frontend"]

volumes:
  postgres_data:
